### ISSUE TITLE
Update lalrpop to fix "packages contain code that will be rejected by a future version of Rust"

### ISSUE THREAD

**Issue by jounathaen** [rp-rs/pio-rs#48]
When using pio-rs, I get the following warning from Cargo:

```
warning: the following packages contain code that will be rejected by a future version of Rust: lalrpop v0.19.8
note: to see what the problems were, use the option `--future-incompat-report`, or run `cargo report future-incompatibilities --id 4`
```

This seems to be fixed in lalrpop-util >= 0.19.9 (https://github.com/lalrpop/lalrpop/issues/702), but this crate still uses 0.19.6.

Thanks!

**Comment by jannic** [comment]
This crate uses lalrpop-util >= 0.19.6. Usually cargo should select the latest available semver-compatible version. That should be 0.19.12 if you start a new project now.

If you get the mentioned error message, it's probably because you have a `Cargo.lock` in your local build tree, which selects an older version of lalrpop-util. In that case, you could fix it by calling `cargo update`, which would update the versions in your `Cargo.lock` file to the latest available versions of all dependencies.
